# Grafana Datasource Provisioning for Prometheus
# This file automatically configures the Prometheus datasource on Grafana startup

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      # Query timeout
      queryTimeout: 60s
      # Default time range for new queries
      # defaultTimeRange: 1h
    version: 1
